/*create database db1;
-- drop database db1;
use db1;
create table table1(ID int);
select * from table1;
create table table2(ID int,name varchar(10),cgpa decimal(3,2));
describe table2;
insert into table2 values(1,"prasad",8.50);
select *from table2;*/
/*alter table table2 add department varchar(5);
alter table table2 drop column cgpa;
create database db2;
use db2;
create table employee(E_ID int,E_Name varchar(30),E_salary int,E_age int);
describe employee;
alter table employee add place varchar(20);
alter table employee drop column E_age;*/
/*use db1;
create table student1(ID int primary key,Name varchar(30),CGPA decimal(3,2));
select *from student1;
describe student1;
insert into student1 values(1,"prasad",8.50);
insert into student1 values(2,"Bhargav",9.00);
insert into student1 values(3,"yaswanth",9.50);
select Name,CGPA from student1 where CGPA>8.70;
create table employee1(emp_id int primary key,ename varchar(20),salary int,job_desc varchar(20));
insert into employee1 values(1,"aaa",50000,"HR");
insert into employee1 values(2,"bbb",35000,"SME");
insert into employee1 values(3,"ccc",75000,"Team lead");
insert into employee1 values(4,"ddd",50000,"analyst");
insert into employee1 values(5,"eee",100000,"Manger");
insert into employee1 values(7,"fff",400000,"CR");
insert into employee1 values(6,"fff",400000,"CEO");
select * from employee1 where ename="fff" and salary>400;
update employee1 set job_desc="automation" where emp_id=7;
select * from employee1;
delete from employee1 where job_desc="SME";
select * from employee1 where ename like "a%";
select * from employee1 where ename like "%a";
select * from employee1 where ename like "%a%";
select * from employee1 where ename like "a%i";*/
create database BooksDB;
use BooksDB;
create table Books(title varchar(30),genre varchar(20),publication_year int,price int);
drop table Books;
create table Books(title varchar(30),author varchar(30),genre varchar(20),publication_year int,price int);
insert into Books values("To Kill a Mockingbird","Harper Lee","Fiction",1960,300);
insert into Books values( "The Alchemist","Paulo Coelho","Inspirational",1988,200);
insert into Books values(" The Da Vinci Code","Dan Brown","Thriller",2003,400);
insert into Books values("The marvel avengers","joss whedon","action",2018,100);
insert into Books values("Civil war","stan lee","strugguling",2019,500);
insert into Books values("infinity war","jack kirby","team work",2020,800);
insert into Books values("End game","zak penn","exellence",2021,900);
insert into Books values("shan chi","Prasad","Historical",2022,1100);
insert into Books values("The legend of 10 rings","Durga","fantasy",2023,1000);
insert into Books values("The secret wars","Jagadeesh","memoir",2024,1500);
select * from Books;
select title from books;
select * from Books where title="infinity war";
update Books set price=1900 where title="The legend of 10 rings";
select * from Books;
delete from Books where title="Civil war";
select * from Books;